# Generated by Django 6.0.2 on 2026-02-04 13:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hastane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ihale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ihale_adi', models.CharField(max_length=255)),
                ('ihale_no', models.CharField(max_length=50)),
                ('tarih', models.DateTimeField()),
                ('is_dogrudan_temin', models.BooleanField(default=False)),
                ('tur', models.CharField(default='Mal', max_length=50)),
                ('il', models.CharField(default='İstanbul', max_length=50)),
                ('ilce', models.CharField(blank=True, max_length=50, null=True)),
                ('durum', models.CharField(default='Acik', max_length=20)),
                ('hastane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihaleler.hastane')),
            ],
        ),
        migrations.CreateModel(
            name='Kalem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=255)),
                ('adet', models.IntegerField()),
                ('birim_fiyat', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ihale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='ihaleler.ihale')),
            ],
        ),
    ]
