# Generated by Django 6.0.2 on 2026-02-05 07:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0002_ihale_guncellenme_tarihi_ihale_olusturan_kullanici_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='kalem',
            name='birim',
            field=models.CharField(default='Adet', max_length=50),
        ),
        migrations.AddField(
            model_name='kalem',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='Mesai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Mesai Tarihi')),
                ('baslangic_saati', models.TimeField(blank=True, null=True, verbose_name='Başlangıç Saati')),
                ('bitis_saati', models.TimeField(blank=True, null=True, verbose_name='Bitiş Saati')),
                ('aciklama', models.TextField(verbose_name='Yapılan İşin Açıklaması')),
                ('dosya', models.FileField(blank=True, null=True, upload_to='mesai_dosyalari/', verbose_name='Görsel/Video')),
                ('olusturulma_tarihi', models.DateTimeField(auto_now_add=True)),
                ('ihale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.ihale', verbose_name='İlgili İhale')),
                ('kullanici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Personel')),
            ],
            options={
                'verbose_name': 'Mesai Kaydı',
                'verbose_name_plural': 'Mesai Kayıtları',
            },
        ),
    ]
