# Generated by Django 6.0.2 on 2026-02-05 09:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0003_kalem_birim_kalem_toplam_fiyat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hastane',
            options={'verbose_name': 'Hastane', 'verbose_name_plural': 'Hastaneler'},
        ),
        migrations.AlterModelOptions(
            name='ihale',
            options={'verbose_name': 'İhale/Dosya', 'verbose_name_plural': 'İhaleler ve Dosyalar'},
        ),
        migrations.AlterModelOptions(
            name='kalem',
            options={'verbose_name': 'İhale Kalemi', 'verbose_name_plural': 'İhale Kalemleri'},
        ),
        migrations.AlterModelOptions(
            name='mesai',
            options={'ordering': ['-tarih', '-olusturulma_tarihi'], 'verbose_name': 'Mesai Kaydı', 'verbose_name_plural': 'Mesai Kayıtları'},
        ),
        migrations.AlterField(
            model_name='hastane',
            name='ad',
            field=models.CharField(max_length=255, verbose_name='Hastane/Kurum Adı'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='durum',
            field=models.CharField(default='Acik', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='hastane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ihaleler.hastane', verbose_name='İlgili Hastane'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='ihale_adi',
            field=models.CharField(max_length=255, verbose_name='İhale Adı'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='ihale_no',
            field=models.CharField(max_length=50, verbose_name='İhale/İKN No'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='il',
            field=models.CharField(default='İstanbul', max_length=50, verbose_name='Şehir'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='ilce',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='İlçe'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='is_dogrudan_temin',
            field=models.BooleanField(default=False, verbose_name='Doğrudan Temin mi?'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='olusturan_kullanici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kaydı Açan'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='tarih',
            field=models.DateTimeField(verbose_name='İhale Tarihi'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='tur',
            field=models.CharField(default='Mal', max_length=50, verbose_name='İhale Türü'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='adet',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='birim',
            field=models.CharField(default='Adet', max_length=50, verbose_name='Birim'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='ihale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kalemler', to='ihaleler.ihale', verbose_name='Bağlı Olduğu İhale'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Fiyat'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='urun_adi',
            field=models.CharField(max_length=255, verbose_name='Ürün/Kalem Adı'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='aciklama',
            field=models.TextField(verbose_name='Yapılan İşin Özeti'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='mesai_dosyalari/%Y/%m/%d/', verbose_name='Görsel/Video Kaydı'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='ihale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.ihale', verbose_name='Bağlı Dosya'),
        ),
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plaka', models.CharField(max_length=20, unique=True, verbose_name='Plaka')),
                ('marka_model', models.CharField(max_length=100, verbose_name='Marka ve Model')),
                ('durum', models.CharField(choices=[('Aktif', 'Aktif'), ('Bakımda', 'Bakımda'), ('Arızalı', 'Arızalı')], default='Aktif', max_length=50, verbose_name='Araç Durumu')),
                ('son_bakim_tarihi', models.DateField(blank=True, null=True, verbose_name='Son Bakım Tarihi')),
                ('notlar', models.TextField(blank=True, null=True, verbose_name='Araç Notları')),
                ('zimmetli_personel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zimmetli_araclar', to=settings.AUTH_USER_MODEL, verbose_name='Zimmetli Personel')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
        migrations.AddField(
            model_name='mesai',
            name='arac',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.arac', verbose_name='Kullanılan Araç'),
        ),
    ]
