# Generated by Django 6.0.2 on 2026-02-05 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0004_alter_hastane_options_alter_ihale_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AracKullanimKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alis_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Alış Tarih/Saat')),
                ('teslim_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Teslim Tarih/Saat')),
                ('teslim_notu', models.TextField(blank=True, null=True, verbose_name='Teslimat/Durum Notu')),
                ('teslim_gorseli', models.ImageField(blank=True, null=True, upload_to='arac_teslimat/%Y/%m/%d/', verbose_name='Teslimat Görseli (Opsiyonel)')),
                ('arac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kullanim_gecmisi', to='ihaleler.arac', verbose_name='Araç')),
                ('personel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Teslim Alan Personel')),
            ],
            options={
                'verbose_name': 'Araç Kullanım Kaydı',
                'verbose_name_plural': 'Araç Kullanım Kayıtları',
                'ordering': ['-alis_tarihi'],
            },
        ),
    ]
