# Generated by Django 6.0.2 on 2026-02-05 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0005_arackullanimkaydi'),
    ]

    operations = [
        migrations.AddField(
            model_name='arackullanimkaydi',
            name='baslangic_km',
            field=models.PositiveIntegerField(default=0, verbose_name='Başlangıç KM'),
        ),
        migrations.AddField(
            model_name='arackullanimkaydi',
            name='bitis_km',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitiş KM'),
        ),
        migrations.AddField(
            model_name='arackullanimkaydi',
            name='ihale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.ihale', verbose_name='İlgili İhale'),
        ),
    ]
