# Generated by Django 6.0.2 on 2026-02-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0006_arackullanimkaydi_baslangic_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kalem',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama/Teknik Özellikler'),
        ),
    ]
