# Generated by Django 6.0.2 on 2026-02-06 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0007_kalem_aciklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrunKutuphanesi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urun_adi', models.CharField(max_length=500, verbose_name='Ürün Adı')),
                ('marka', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marka')),
                ('teknik_sartname_metni', models.TextField(blank=True, null=True, verbose_name='Teknik Özellik Arşivi')),
                ('gorsel', models.ImageField(blank=True, null=True, upload_to='urun_arsivi/', verbose_name='Ürün Görseli')),
                ('son_alis_fiyati', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Son Alış Fiyatı (Mikro)')),
            ],
            options={
                'verbose_name': 'Ürün Kütüphanesi',
                'verbose_name_plural': 'Ürün Kütüphanesi',
            },
        ),
        migrations.AlterModelOptions(
            name='mesai',
            options={'ordering': ['-tarih', '-olusturulma_tarihi'], 'verbose_name': 'Mesai/İş Kaydı', 'verbose_name_plural': 'Mesai ve İş Kayıtları'},
        ),
        migrations.RemoveField(
            model_name='kalem',
            name='aciklama',
        ),
        migrations.AddField(
            model_name='ihale',
            name='kar_orani',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Kâr Oranı (%)'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='odeme_alindi_mi',
            field=models.BooleanField(default=False, verbose_name='Devlet Ödemesi Alındı mı?'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='odeme_tarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Ödemenin Alındığı Tarih'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='toplam_maliyet',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Gerçekleşen Maliyet'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='toplam_teklif_bedeli',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Teklif (KDV Hariç)'),
        ),
        migrations.AddField(
            model_name='kalem',
            name='fatura_no',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mikro Fatura No'),
        ),
        migrations.AddField(
            model_name='kalem',
            name='maliyet_birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Gerçek Alış Fiyatı'),
        ),
        migrations.AddField(
            model_name='kalem',
            name='teknik_sartname_ozeti',
            field=models.TextField(blank=True, null=True, verbose_name='Bu İhale İçin Teknik Şartname Özeti'),
        ),
        migrations.AlterField(
            model_name='ihale',
            name='durum',
            field=models.CharField(choices=[('Acik', 'Açık/Devam Ediyor'), ('Kazandik', 'Kazanıldı'), ('Kaybettik', 'Kaybedildi'), ('Tamamlandi', 'İş Tamamlandı/Teslim Edildi'), ('Iptal', 'İptal Edildi')], default='Acik', max_length=20, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='birim_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Teklif Birim Fiyat'),
        ),
        migrations.AlterField(
            model_name='kalem',
            name='toplam_fiyat',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Toplam Teklif Fiyatı'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='aciklama',
            field=models.TextField(verbose_name='Yapılan İş/Bakım Özeti'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='dosya',
            field=models.FileField(blank=True, null=True, upload_to='mesai_dosyalari/%Y/%m/%d/', verbose_name='İş Görseli/Video'),
        ),
        migrations.AlterField(
            model_name='mesai',
            name='ihale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.ihale', verbose_name='Bağlı Dosya/İhale'),
        ),
        migrations.AddField(
            model_name='kalem',
            name='kutuphane_urunu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ihaleler.urunkutuphanesi', verbose_name='Kütüphane Eşleşmesi'),
        ),
    ]
