# Generated by Django 6.0.2 on 2026-02-06 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0008_urunkutuphanesi_alter_mesai_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihale',
            name='cetvel_dosya',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/cetveller/', verbose_name='Birim Fiyat Cetveli (PDF/Excel)'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='sartname_dosya',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/sartnameler/', verbose_name='Teknik Şartname (PDF)'),
        ),
    ]
