# Generated by Django for multiple cetvel/sartname files

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ihaleler', '0014_ihale_verilen_teklif_dosya'),
    ]

    operations = [
        migrations.AddField(
            model_name='ihale',
            name='cetvel_dosya_2',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/cetveller/', verbose_name='Birim Fiyat Cetveli 2'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='cetvel_dosya_3',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/cetveller/', verbose_name='Birim Fiyat Cetveli 3'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='sartname_dosya_2',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/sartnameler/', verbose_name='Teknik Şartname 2'),
        ),
        migrations.AddField(
            model_name='ihale',
            name='sartname_dosya_3',
            field=models.FileField(blank=True, null=True, upload_to='ihaleler/sartnameler/', verbose_name='Teknik Şartname 3'),
        ),
    ]
